# Generated by Django 3.1.1 on 2021-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_en', models.TextField(verbose_name='About company Ru')),
                ('description_ru', models.TextField(verbose_name='About company En')),
                ('logo', models.CharField(max_length=1000, verbose_name='Company Logo')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': '1.About',
            },
        ),
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faq', models.URLField(verbose_name='Faq link')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': '2.FAQ LINK',
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=1000, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': '4.Photo',
            },
        ),
        migrations.CreateModel(
            name='PriceListModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pirce_list', models.ImageField(upload_to='media', verbose_name='Pirce list')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': '3.Price List',
            },
        ),
        migrations.CreateModel(
            name='SerificateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=1000, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Sertificate',
                'verbose_name_plural': '6. Sertificates',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.CharField(max_length=1000, verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': '5. Videos',
            },
        ),
    ]
