# Generated by Django 3.1.1 on 2021-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistmodel',
            name='pirce_list',
            field=models.CharField(max_length=1000, verbose_name='Pirce list'),
        ),
    ]
