# Generated by Django 3.1.1 on 2021-10-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20211027_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serificatemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='description',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description EN'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description RU'),
        ),
        migrations.AddField(
            model_name='serificatemodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description EN'),
        ),
        migrations.AddField(
            model_name='serificatemodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description RU'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description EN'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description RU'),
        ),
    ]
