# Generated by Django 3.1.14 on 2021-12-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=300, verbose_name='Category name En')),
                ('category_name_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Category name Ru')),
                ('category_photo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Category photo')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': '2.Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=300, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.CharField(blank=True, choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=300, null=True, verbose_name='User Type')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': '1.Users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Product name En')),
                ('name_ru', models.CharField(default='S', max_length=200, verbose_name='Product name Ru')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description Ru')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description En')),
                ('photo', models.CharField(max_length=1000, verbose_name='Photo')),
                ('photo_2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Certificate photo 1')),
                ('photo_3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Certificate photo 2')),
                ('photo_4', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Certificate photo 3')),
                ('photo_5', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Certificate photo 4')),
                ('photo_6', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Certificate photo 5')),
                ('description_2_ru', models.TextField(blank=True, max_length=3000, null=True, verbose_name='About product Ru')),
                ('description_2_en', models.TextField(blank=True, max_length=3000, null=True, verbose_name='About product En')),
                ('category_name_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Category Ru')),
                ('category_code', models.CharField(blank=True, max_length=300, verbose_name='Unnecassary category-code')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcategory', verbose_name='Category En')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '3.Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('email', models.CharField(blank=True, max_length=400, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=400, null=True, verbose_name='Phone')),
                ('company_name', models.CharField(max_length=400, verbose_name='Company name')),
                ('address', models.CharField(max_length=400, verbose_name='Address company')),
                ('purchases', models.TextField(verbose_name='Purchases')),
                ('total', models.BigIntegerField(verbose_name='Total')),
                ('is_success', models.BooleanField(blank=True, default=False, null=True, verbose_name='Delivered ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': '5.Orders',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(verbose_name='Amount')),
                ('total', models.BigIntegerField(verbose_name='Total')),
                ('is_success', models.BooleanField(blank=True, null=True, verbose_name='Purchased ?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': '4.Carts',
            },
        ),
    ]
