# Generated by Django 3.1.14 on 2022-04-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220416_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=300, verbose_name='Ismi')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktivligi')),
                ('is_admin', models.CharField(blank=True, choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=300, null=True, verbose_name='Foydalanuvchi turi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': '1.Foydalanuvchilar',
            },
        ),
    ]
